SELECT * FROM public.customer
SELECT * from customer

--1) What is total Revenue generated by male/female customers 
 select gender ,
 SUM (purchase_amount) AS total_revenue 
 from customer 
 group by gender ; 

--2) Which customers uses a discount but still spent more than the avg purchase amount 
 select customer_id , purchase_amount
 from customer 
 where discount_applied = 'Yes'
    and purchase_amount > (select avg(purchase_amount) from customer);

--3) Top 5  products with the highest avg review rating
 select item_purchased, (round (avg(review_rating::numeric),2)) as avg_rating
 from customer 
 group by item_purchased
 order by avg(review_rating)desc
 limit 5;

--4) Compare the avg purchase  amount between   Standard and Express  shipping
select shipping_type , 
round(avg(purchase_amount),2) as avg_shipping_amount 
from customer 
where shipping_type in ('Standard' , 'Express')
group by shipping_type 

--5) Do subscribe customers spend more compare avg  spend and  total revenue between subscribers and non-subscribriras
select subscription_status ,
count(customer_id) as totalnumber_of_customers ,
sum(purchase_amount) as total_revenue,
round(avg(purchase_amount),2) as avg_spend  
from customer 
group by subscription_status 
order by total_revenue , avg_spend desc ;

--6)  which are 5 products have highest percentage of purchases with discount applied
  select item_purchased , 
  round  (100 * sum (case when discount_applied = 'Yes' then 1 else 0 end )/count(*),2) as discount_price
  from customer 
  group by item_purchased 
  order by discount_price desc 
  limit 5; 
 
--7)  Segment Customers in  New, Returning and loyal based on their  perevious purchase and show  count of each segnent

 with customer_type as (
 select previous_purchases , customer_id ,
 case 
      when previous_purchases = 1 then 'new'
      when previous_purchases  between 2 and 10 then 'returning'
	  else 'loyal'
	  end as customer_segment 
 from customer 
 )

select customer_segment , count(*) as "total_customers"
from customer_type 
group by customer_segment ; 

--8) Top 3 most purchased products. Within each category 
with item_counts as (
select item_purchased , category ,
count(customer_id) as total_customers ,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer 
group by category , item_purchased 
)
select item_purchased  ,category , total_customers , item_rank  
from item_counts 
where item_rank <= 3;

--9) Customers  Who are repeat buyers (more than 5 times  previous purchase) are more libely to subscribe 
  select  subscription_status , count(customer_id) as repeat_buyers
  from customer 
  where previous_purchases > 5 
  group by subscription_status ;
  
--10) Revenue contribution  of cach age group
select age_group , sum(purchase_amount) as total_revenue 
from customer
group by age_group 
order by total_revenue desc ; 
